drop table if exists emails;
drop table if exists election_staffs;
drop table if exists votes;
drop table if exists register;
drop table if exists voting_center_sch;
drop table if exists voting_centers;
drop table if exists ballots;
drop table if exists wonderland_individuals;
drop table if exists places;